### ISSUE TITLE
Module (DoctrineMoneyModule) could not be initialized.

### ISSUE THREAD

**Issue by olekhy** [zfbrasil/doctrine-money-module#12]
on 0.1 no problem after update on dev-master we get an error from zf module manager:

error:
```
Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (DoctrineMoneyModule) could not be initialized.' in /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 197

Zend\ModuleManager\Exception\RuntimeException: Module (DoctrineMoneyModule) could not be initialized. in /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 197

Call Stack:
    0.0002     232840   1. {main}() /home/o/p/public/index.php:0
    0.0124     798600   2. Zend\Mvc\Application::init() /home/o/p/public/index.php:17
    0.0354    1995344   3. Zend\ModuleManager\ModuleManager->loadModules() /home/o/p/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php:252
    0.0354    1995728   4. Zend\EventManager\EventManager->trigger() /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php:115
    0.0354    1996288   5. Zend\EventManager\EventManager->triggerListeners() /home/o/p/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:207
    0.0357    2017784   6. call_user_func() /home/o/p/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
    0.0357    2017952   7. Zend\ModuleManager\ModuleManager->onLoadModules() /home/o/p/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:468
    0.0563    2758624   8. Zend\ModuleManager\ModuleManager->loadModule() /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php:96
    0.0563    2758624   9. Zend\ModuleManager\ModuleManager->loadModuleByName() /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php:169

PHP Fatal error:  Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (DoctrineMoneyModule) could not be initialized.' in /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php:197
Stack trace:
#0 /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(169): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent))
#1 /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php(96): Zend\ModuleManager\ModuleManager->loadModule('DoctrineMoneyMo...')
#2 [internal function]: Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent))
#3 /home/o/p/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\ModuleManager\ModuleEvent))
#4 /home/o/p/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventMana in /home/o/p/vendor/zendframework/zendframework/library/Zend/ModuleManager/ModuleManager.php on line 197
```
dump in 
```php

// \Zend\ModuleManager\ModuleManager::loadModuleByName  

//var_dump($module, $event);
bool(false)
class Zend\ModuleManager\ModuleEvent#49 (7) {
  protected $module =>
  class SpiffyNavigation\Module#121 (0) {
  }
  protected $moduleName =>
  string(19) "DoctrineMoneyModule"
  protected $configListener = ..........
```

WTF moduleName is differ to module ;)

**Comment by danizord** [comment]
@olekhy I think this is because we prepended a vendor namespace (ZFBrasil) in current master. Try registering `ZFBrasil\DoctrineMoneyModule` in your `application.config.php`.

@gabrielsch @fabiocarneiro we should probably consider removing the vendor namespace to avoid compatibility breaks, what do you think?
